# This workflow will deploy into Divio Test environment on a push event to the develop branch

name: Divio Test environment Deployment

# Assigning environment variables of the secret keys for easy access
env:
  API_TOKEN: ${{ secrets.API_TOKEN }}
  PROJECT_SLUG: ${{ secrets.PROJECT_SLUG }}

on:
 push:
  branches: [ develop ]

# jobs run to execute the workflow
jobs:

# This workflow contains a single job called "deploy" and runs on ubuntu-latest
 deploy:
  runs-on: ubuntu-latest
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
  # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
  - uses: actions/checkout@v2
  # Use a script to get the necessary credentials, deploy and broadcast the success of the deployment
  - name: Deploy and report the success of the deployment
    run: | 
      chmod +x "${GITHUB_WORKSPACE}/cd-test.sh"
      ./cd-test.sh
   
